In [1]:
import numpy as np

In [40]:
def G(theta):
    res = np.empty([2,2])
    res[0, 0] = theta[1]**2 - theta[0]
    res[0, 1] = -theta[0] * theta[1]
    res[1, 0] = -theta[0] * theta[1]
    res[1, 1] = theta[0]**2
    return - res / (2 * theta[0]**3)

def G_inv(eta):
    res = np.empty([len(eta), len(eta)])
    res[0, 0] = 1/2
    res[0, 1] = - eta[1]
    res[1, 0] = - eta[1]
    res[1, 1] = eta[0] + eta[1]**2
    return res / (eta[0] - eta[1]**2)**2


def G_dagger(thetas):
    res = G(thetas[0, :])
    for theta in thetas[1:, :]:
        res += G(theta)
    return res

def lambda_(theta):
    return np.linalg.det(G(theta))

def xi(i, thetas):
    return np.sqrt(lambda_(thetas[i, :])) * np.sqrt(G_dagger(thetas)) @ thetas[i, :]

def xis(thetas):
    res = [xi(0, thetas)]
    for i in range(1, n):
        res.append(xi(i, thetas))
    return np.array(res)


In [49]:
G(np.array([1, 2]))
np.linalg.inv(G(thetas[0, :]))

array([[  6.21061399, -10.48105657],
       [-10.48105657,  21.21224849]])

In [51]:
G_inv(np.array([1,2]))*9

array([[ 0.5, -2. ],
       [-2. ,  5. ]])

In [27]:
from sklearn.decomposition import PCA

def K(h, xis):
    pca = PCA(n_components=2)
    res = pca.fit_transform(xis)
    return res[:h, :].T

In [28]:
n = 10
mus = np.array([np.random.rand()*2 - 1 for mu in range(n)])
sigmas = np.array([np.random.rand() + 0.5 for mu in range(n)])

theta_1s = - 1 / (2 * sigmas**2)
theta_2s = mus / sigmas**2
thetas = np.array([theta_1s, theta_2s]).T

eta_1s = mus**2 + sigmas**2
eta_2s = mus
etas = np.array([eta_1s, eta_2s]).T

In [29]:
h = 1
# Get initial U and w_tilda
U = np.linalg.inv(np.sqrt(G_dagger(thetas))) @ K(h, xis(thetas))

In [30]:
print(xis(thetas))
np.linalg.inv(np.sqrt(G_dagger(thetas)))
K(h, xis(thetas))

[[-0.21378099  0.84038061]
 [-1.79387026  0.25037963]
 [-2.62723984 -2.02848343]
 [-1.03551492  0.81769134]
 [-1.17056602  0.47283866]
 [-2.4069258  -1.62256125]
 [-2.67119796 -0.87185778]
 [-1.38747549  0.22052937]
 [-2.63024793 -1.04442648]
 [-0.91235106  0.1655756 ]]


array([[-1.80076137],
       [-0.42040169]])

In [137]:
np.linalg.inv(np.sqrt(G_dagger(thetas))) @ np.array([[1],[1]])

<ipython-input-137-bbf17c4ffe08>:1: RuntimeWarning: invalid value encountered in sqrt
  np.linalg.inv(np.sqrt(G_dagger(thetas))) @ np.array([[1],[1]])


array([[nan],
       [nan]])

In [31]:
G_dagger(thetas)

array([[20.11667739,  5.38884455],
       [ 5.38884455,  7.27728727]])